#!/usr/bin/env ruby

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'rubygems'
require 'bundler/setup'
require 'dotenv'
require 'daemons'
require 'slnky/chef'
Dotenv.load

env = ARGV[0]

# Become a daemon
# Daemons.daemonize if env == 'production'

Slnky::Chef::Service.new(ENV['SLNKY_URL'], environment: env).start
